@startuml "MII_Datenmodell_Seltene_Erkrankungen_logisch"
skinparam Linetype ortho

title Modulvorschau MII Erweiterungsmodul Seltene Erkrankungen
package "MII_Datenmodell_Seltene_Erkrankungen" {

  package MII_Person #33CCFF{
    object MII_Patient {
      o Geschlecht
      o Geburtstag/Alter

    }
    object Vitalstatus  {
      o Datum
      o Status
    }

  }
  package "MII_Modul_Diagnose" #33CCFF {
    object MII_Diagnose {
      o code: ICD10GM
      o code: Orphacode
      o Alter bei Diagnose
      o Status (Verdacht, gesichert..)
    }
  }
 
  package "MII_Modul_Seltene_Erkrankungen" #FFEE22{
    object MII_Diagnose_SE {
      o code: ICD10GM
      o code: Orphacode
    }
    object MII_MolGen_Variante_SE  {
      o code: HGVS
    }
    object MII_Familienanamnese_SE
    object Familienmitglied {
      o Verwandtschaftsverhaeltnis
      o Geschlecht
      o gleiche Erkrankung
      o andere Erkrankung
    }
    object MII_Symptom_Observation_SE  {
      o code: Human Phenotype Ontology (HPO)
      o value: Presence/Absence
      o date: Datum der Untersuchung
      o period: Zeitraum der Symptomatik  
      o startAge: Alter bei Symptombeginn
      o change: Änderung
    }
    object MII_Symptom_Condition_SE

    object Untersuchung {
      o Koerperliche_Untersuchung
      o Diagnostik
      o Therapiestatus
      o Datum
    }
    object Therapiestatus {
      o Therapieempfehlungen
      o Durchgeführte_Therapien
    }
    object Therapieempfehlungen{
      o Therapieart
      o off-label
      o Studie
    }
    object Durchgeführte_Therapien {
      o Therapieart
      o Startdatum
      o Enddatum
      o Grund_Beendigung
      o off-label
      o Studie
    }
  }
  package "MII_Modul_ICU" #00DD00{
    object Koerpergewicht
    object Koerpergroeße
  }
  package "MII_Modul_Labor" #00DD00 {
    object Laborparameter
  }
  package "MII_Modul_Studie" #00DD00 {
    object MII_Studie
  }

  package "MII_Modul_Molekulargenetischer_Befundbericht" #33CCFF{
    object MII_MolGen_Variante {
      o code: HGVS
    }
    object MII_MolGen_Familienanamnese
  }
   package "MII_Modul_Symptom_klinischer_Phänotyp" #33CCFF{
    object MII_Symptom_Observation
    object MII_Symptom_Condition
  }



  MII_Diagnose <|-down- MII_Diagnose_SE
  MII_MolGen_Variante <|-down-- MII_MolGen_Variante_SE
  MII_MolGen_Familienanamnese <|-up-- MII_Familienanamnese_SE
  MII_Symptom_Observation <|-right- MII_Symptom_Observation_SE
  MII_Symptom_Condition <|-up- MII_Symptom_Condition_SE

  MII_Familienanamnese_SE "1..*" o-- "1..1" Familienmitglied
  Untersuchung "0..*" o-up- "0..1" Laborparameter
  Untersuchung "0..*" o-- "0..*" MII_Diagnose_SE
  Untersuchung "0..*" o-- "0..*" MII_MolGen_Variante_SE
  Untersuchung "0..*" o-- "0..*" MII_Symptom_Observation_SE
  Untersuchung "0..*" o-- "0..*" MII_Familienanamnese_SE
  Untersuchung "0..*" o-up- "0..*" Koerpergewicht
  Untersuchung "0..*" o-up- "0..*" Koerpergroeße
  Untersuchung "0..*" o-- "0..*" MII_Symptom_Condition_SE
  Untersuchung "0..*" o-- "0..*" Therapiestatus  
  Therapiestatus "0..*" o-down- "1..1" Therapieempfehlungen
  Therapiestatus "0..*" o-down- "1..1" Durchgeführte_Therapien
  Therapieempfehlungen "0..*" o-down- "0..*" MII_Studie
  Durchgeführte_Therapien "0..*" o-down- "0..*" MII_Studie

}


@enduml
