@startuml MII_SE_Overview
skinparam Linetype ortho
'skinparam linetype polyline

title Modulvorschau MII Erweiterungsmodul Seltene Erkrankungen

package MII_Modul_Diagnose {
    object MII_Diagnose {
        + code: ICD10GM
        + code: Orphacode
        + Alter bei Diagnose
        + Status (Verdacht, gesichert..)
    }
}



package MII_Modul_Molekulargenetischer_Befundbericht {
    object MII_MolGen_Variante {
        + code: HGVS
    }
    object MII_MolGen_Familienanamnese
}

package MII_Modul_Symptom_klinischer_Phänotyp {
    object MII_Symptom_Observation
    object MII_Symptom_Condition
 
}

package MII_Modul_Seltene_Erkrankungen {
    object MII_Diagnose_SE {
        + code: ICD10GM
        + code: Orphacode
    }
    object MII_Symptom_Observation_SE
    object MII_Symptom_Condition_SE {
    + code: Human Phenotype Ontology (HPO)
    }
    object MII_Familienanamnese_SE 
    object Familienmitglied {
            + Verwandtschaftsverhaeltnis
            + Geschlecht
            + Erkrankung
        }
    

    object MII_MolGen_Variante_SE {
         + code: HGVS
    }
    
    package HL7_DE_Basisprofile {
    object Koerpergroeße
    object Koerpergewicht
    }

}

MII_Diagnose -down--> MII_Diagnose_SE
MII_Symptom_Observation -down--> MII_Symptom_Observation_SE
MII_Symptom_Condition -down--> MII_Symptom_Condition_SE
MII_MolGen_Familienanamnese -down--> MII_Familienanamnese_SE
MII_MolGen_Variante -down--> MII_MolGen_Variante_SE
MII_Familienanamnese_SE o-down- Familienmitglied 

@enduml