Logical: MII_LM_SE
Parent: Element
Id: mii-lm-seltene
Title: "MII LM SE"
Description: "MII LogicalModel Modul Seltene Erkraknungen"
* insert Publisher
* insert PR_CS_VS_Version
* ^url = "https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/LogicalModel/Seltene"
* anamneseUndDiagnostik 0..* BackboneElement "Diagnose"
  * untersuchungsdatum 0..1 date "Untersuchungsdatum" "Datum der durchgeführten Untersuchung eines SE-Patienten."
  * untersuchungsanlass 0..1 code "Untersuchungsanlass" "Grund fuer den Besuch des SE-Patienten."
  * phaenotypisierung 0..* BackboneElement "Phaenotypisierung"
    * hpoTerm 0..* code "HPO-Term des Symptoms" "Phaenotypisierung des SE-Patienten mittels HPO-Term (Human Phenotype Ontology) oder anderer Terminologien (SNOMED CT, ICD-10, LOINC)."
    * hpoExcluded 0..1 boolean "HPO-Term ausgeschlossen" "Gibt an, ob das HPO-Merkmal explizit ausgeschlossen wurde (negated finding). Abgeleitet aus valueCodeableConcept: LOINC LA9634-2 'Absent' = true, LA9633-4 'Present' = false. Folgt HL7 Phenomics IG Muster."
    * hpoStatus 0..1 code "Status HPO-Term" "Status oder Schweregrad des Phaenotyps (Present/Absent/Severity)."
    * hpoVersion 0..1 code "Version HPO-Term" "Kennzeichnung der genutzten Version des ausgewaehlten HPO-Terms."
    * zeitraumSymptom 0..* BackboneElement "Zeitraum des Symptom"
      * zeitraumSymptom 0..* dateTime "Startdatum des Symptoms" "Startdatum und bei Bedarf Periode der ersten Symptome/Anzeichen." // Überprüfung 2 Datentypen period und dateTime
      * lebensphase 0..* code "Lebensphase Symptom" "Lebensphase, in der das Symptom aufgetreten ist."
      * alterSymptom 0..1 integer "Alter Symptom" "Alter beim Auftreten der ersten Symptome/Anzeichen."
    * verlaufSymptom 0..1 code "Verlauf Symptom" "Aenderung des Verlaufs des Symptoms seit der vorherigen Untersuchung."
  * klinischeDiagnose 0..* BackboneElement "Zeitraum der klinischen SE-Diagnose"  
    * zeitpunktKlinischeDia 0..1 code "Zeitpunkt klinische SE-Diagnose" "Auswahl der Altersangabe (Lebensphase) des Zeitpunktes der klinsichen SE-Diagnose."
    * feststellungsdatumKlinischeDia 0..1 date "Feststellungsdatum klinische SE-Diagnose" "Datum, an dem die klinische SE-Diagnose festgestellt wurde."
    * alterKlinischeDia 0..1 integer "Alter bei klinischer SE-Diagnose" "Alter, in dem die klinische SE-Diagnose gestellt wurde."
  * genetischeDiagnose 0..* BackboneElement "Zeitraum der genetischen SE-Diagnose"  
    * zeitpunktGenDia 0..1 code "Zeitpunkt genetische SE-Diagnose" "Auswahl der Altersangabe (Lebensphase) des Zeitpunktes der genetischen SE-Diagnose."
    * feststellungsdatumGenDia 0..1 date "Feststellungsdatum genetische SE-Diagnose" "Datum, an dem die genetische SE-Diagnose festgestellt wurde."
    * alterGenDia 0..1 integer "Alter bei genetischer SE-Diagnose" "Alter, in dem die genetische SE-Diagnose gestellt wurde."
  * genDiaFehlendePenetranz 0..* code  "Genetische Diagnose mit fehlender Penetranz" "Gibt an, ob bei einer genetischen Diagnose die Penetranz (Wahrscheinlichkeit Genotyp bildet Phaenotyp aus) fehlt"
  * methodeDiagnosestellung 0..* code "Methode der Diagnosestellung" "Gibt an, welche Methode zur Diagnosestellung verwendet wurde."
* koerperlicheUntersuchung 0..* BackboneElement "Körperliche Untersuchung"
  * koerpergewicht 0..* BackboneElement "Körpergewicht"
    * koerpergewicht 0..1 decimal "Körpergewicht in kg" "Körpergewicht des SE-Patienten in kg (aus MII ICU Modul)."
    * datumKoerpergewicht 0..1 dateTime "Datum Körpergewicht" "Datum der Körpergewichtsmessung."
  * koerpergroesse 0..* BackboneElement "Körpergröße"
    * koerpergroesse 0..1 decimal "Körpergröße in cm" "Körpergröße des SE-Patienten in cm (aus MII ICU Modul)."
    * datumKoerpergroesse 0..1 dateTime "Datum Körpergröße" "Datum der Körpergrößenmessung."
  * bmi 0..* BackboneElement "BMI"
    * bmi 0..1 decimal "BMI SE-Patient" "BMI des SE-Patienten."
    * datumBMI 0..1 dateTime "Datum des BMI" "Datum, an dem der BMI (Body Mass Index) berechnet wurde."
  * kopfumfang 0..* BackboneElement "Kopfumfang"
    * kopfumfang 0..1 decimal "Kopfumfang in cm" "Kopfumfang des SE-Patienten in cm."
    * datumKopfumfang 0..1 dateTime "Datum Kopfumfang" "Datum der Kopfumfangsmessung."
  * bauchumfang 0..* BackboneElement "Bauchumfang"
    * bauchumfang 0..1 decimal "Bauchumfang in cm" "Bauchumfang des SE-Patienten in cm."
    * datumBauchumfang 0..1 dateTime "Datum Bauchumfang" "Datum der Bauchumfangsmessung."
  * hueftumfang 0..* BackboneElement "Hüftumfang"
    * hueftumfang 0..1 decimal "Hüftumfang in cm" "Hüftumfang des SE-Patienten in cm."
    * datumHueftumfang 0..1 dateTime "Datum Hüftumfang" "Datum der Hüftumfangsmessung."
  * blutgruppe 0..1 code "Blutgruppe" "Blutgruppe des SE-Patienten (AB0 und Rhesusfaktor)."
* persoenlicheInfosIndexpatient 0..* BackboneElement "Persoenliche Informationen des Indexpatienten"
  * tod 0..1 BackboneElement "Tod"
    * sterbedatum 0..1 date "Sterbedatum" "Sterbedatum des Indexpatienten."
    * anSEVerstorben 0..1 code "An der SE verstorben" "Angabe, ob der Indexpatient an der SE verstorben ist."
    * andereTodesursache 0..* code "Todesursache" "Kodierung der Todesursache soweit bekannt (ICD-10-GM, ORPHAcodes)."
* familienanamnese 0..* BackboneElement "Familienanamnese"
  * verwandtschaftsverhaeltnis 0..1 code "Verwandtschaftsverhaeltnis" "Biologisches Verwandtschaftsverhaeltnis des Familienmitglieds zum Indexpatienten."
  * geschlecht 0..1 code "Geschlecht" "Geschlecht des Familienmitglieds."
  * gleicheSE 0..* code "Gleiche SE" "Gibt an, ob das Familienmitglied an der gleichen SE leidet wie der Indexpatient."
  * andereSE 0..* code "Andere SE" "Gibt an, ob das Familienmitglied an einer anderen SE leidet als der Indexpatient."
  * penetranz 0..1 code "Penetranz" "Gibt an, ob bei fehlender klinscher Penetranz (Wahrscheinlichkeit Genotyp bildet Phaenotyp aus) die genetische Diagnose vorliegt."
  * familienmitgliedVerstorben 0..1 code "Familienmitglied verstorben" "Gibt an, ob das Familienmitglied verstorben ist."
* therapieForschung 0..* BackboneElement "Therapie und Forschung"
  * offLabel 0..* BackboneElement "Off-Label-Gabe"
    * offLabelGabe 0..1 code "Off-Label-Gabe" "Gibt an, ob eine Off-Label-Gabe vorliegt."
    * offLabelMedikament 0..* code "Off-Label-Medikament" "Gibt an, welches Medikament Off-Label gegeben wurde."
  * studie 0..* BackboneElement "Studie" 
    * studienID 0..1 Identifier "Studien-ID" "Eindeutige Identifikation der Studie, an der der SE-Patient teilgenommen hat."
    * studienStatus 0..1 code "Studienstatus" "Aktueller Status der Studie, an der der SE-Patient teilgenommen hat (Abgeschlossen, Fortlaufend)."
    * studienzeitraum 0..1 period "Studienzeitraum" "Zeitraum, in dem der SE-Patient an der Studie teilgenommen hat."
  * therapie 0..* BackboneElement "Therapie"
    * therapieempfehlung 0..* code "Eine Therapieempfehlung beschreibt eine spezifische Maßnahme oder Strategie. Sie kann eigenständig vorliegen oder referenziert einem Therapieplan zugeordnet werden. Art der Therapieempfehlung" "Gibt an, welche Therapieempfehlung vorliegt."
    * durchgefuehrteTherapie 0..* code "Durchgefuehrte Therapie" "Tatsaechlich durchgeführte Therapie des SE-Patienten (mit oder ohne Studie mit heilender Intention)."
    * startdatumTherapie 0..1 date "Startdatum Therapie" "Datum, an dem die Therapie begonnen hat."
    * enddatumTherapie 0..1 date "Enddatum Therapie" "Datum, an dem die Therapie beendet wurde."
    * grundEndeTherapie 0..* code "Grund Ende Therapie" "Gibt an, warum die Therapie beendet wurde (z.B. Nebenwirkungen, keine Wirkung)."
      
// --- Logical Model mappings TEMPORARILY DISABLED for the IG Publisher build ---
// The IG Publisher throws 'NullPointerException: tgt is null' while rendering the
// maps fragment (StructureDefinition-mii-lm-seltene-maps-*.xhtml); adding Target:
// uris did not resolve it. Content preserved below; re-enable after diagnosis.
/*
Mapping: SE-vomLogicalModelzuFHIR
Id: FHIR
Title: "SE LogicalModel FHIR Mapping"
Source: MII_LM_SE
Target: "http://hl7.org/fhir"
* anamneseUndDiagnostik -> "Condition | Observation | ClinicalImpression"
  * untersuchungsdatum -> "ClinicalImpression.effectiveDateTime"
  * untersuchungsanlass -> "ClinicalImpression.reasonCode"
  * phaenotypisierung -> "Observation.where(code.coding.exists(system='http://purl.obolibrary.org/obo/hp.owl')) | Condition.where(code.coding.exists(system='http://purl.obolibrary.org/obo/hp.owl')) | Observation (SNOMED CT, ICD-10, LOINC)"
    * hpoTerm -> "Observation.code | Condition.code"
    * hpoExcluded -> "Observation.valueCodeableConcept (true wenn LOINC#LA9634-2 'Absent', false wenn LA9633-4 'Present')"
    * hpoStatus -> "Observation.valueCodeableConcept (LOINC Present/Absent oder HPO Severity codes) | Condition.verificationStatus"
    * hpoVersion -> "Observation.code.coding.version | Condition.code.coding.version"
    * zeitraumSymptom -> "Condition.onset[x] | Observation.effective[x]"
      * zeitraumSymptom -> "Condition.onsetDateTime | Condition.onsetPeriod | Observation.effectivePeriod"
      * lebensphase -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ext-seltene-onset-age').valueCodeableConcept"
      * alterSymptom -> "Condition.onsetAge | Observation.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ext-seltene-onset-age').valueAge"
    * verlaufSymptom -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ext-seltene-phenotypic-pattern').valueCodeableConcept | Observation.interpretation"
  * klinischeDiagnose -> "Condition.where(category.coding.exists(code='clinical'))"
    * zeitpunktKlinischeDia -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ext-seltene-onset-age').valueCodeableConcept"
    * feststellungsdatumKlinischeDia -> "Condition.extension.where(url='http://hl7.org/fhir/StructureDefinition/condition-assertedDate').valueDateTime"
    * alterKlinischeDia -> "Condition.onsetAge"
  * genetischeDiagnose -> "Condition.where(category.coding.exists(code='genetic'))"
    * zeitpunktGenDia -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ext-seltene-onset-age').valueCodeableConcept"
    * feststellungsdatumGenDia -> "Condition.extension.where(url='http://hl7.org/fhir/StructureDefinition/condition-assertedDate').valueDateTime"
    * alterGenDia -> "Condition.onsetAge"
  * genDiaFehlendePenetranz -> "Condition.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ex-seltene-penetrance').valueCodeableConcept"
  * methodeDiagnosestellung -> "Observation.method"
* koerperlicheUntersuchung -> "Observation"
  * koerpergewicht -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='29463-7')) | Profile: https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/Koerpergewicht"
    * koerpergewicht -> "Observation.valueQuantity.value"
    * datumKoerpergewicht -> "Observation.effectiveDateTime"
  * koerpergroesse -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='8302-2')) | Profile: https://www.medizininformatik-initiative.de/fhir/ext/modul-icu/StructureDefinition/Koerpergroesse"
    * koerpergroesse -> "Observation.valueQuantity.value"
    * datumKoerpergroesse -> "Observation.effectiveDateTime"
  * bmi -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='39156-5'))"
    * bmi -> "Observation.valueQuantity.value"
    * datumBMI -> "Observation.effectiveDateTime"
  * kopfumfang -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='9843-4')) | Profile: http://fhir.de/StructureDefinition/observation-de-vitalsign-kopfumfang"
    * kopfumfang -> "Observation.valueQuantity.value"
    * datumKopfumfang -> "Observation.effectiveDateTime"
  * bauchumfang -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='8280-0'))"
    * bauchumfang -> "Observation.valueQuantity.value"
    * datumBauchumfang -> "Observation.effectiveDateTime"
  * hueftumfang -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='62409-8'))"
    * hueftumfang -> "Observation.valueQuantity.value"
    * datumHueftumfang -> "Observation.effectiveDateTime"
  * blutgruppe -> "Observation.where(code.coding.exists(system='http://loinc.org' and code='882-1')).valueCodeableConcept"
* persoenlicheInfosIndexpatient -> "Patient"
  * tod -> "Patient.deceased[x]"
    * sterbedatum -> "Patient.deceasedDateTime"
    * anSEVerstorben -> "Condition.extension.where(url='http://hl7.org/fhir/StructureDefinition/condition-assertedDate')"
    * andereTodesursache -> "Condition.where(category.coding.exists(code='cause-of-death')).code"
* familienanamnese -> "FamilyMemberHistory"
  * verwandtschaftsverhaeltnis -> "FamilyMemberHistory.relationship"
  * geschlecht -> "FamilyMemberHistory.sex"
  * gleicheSE -> "FamilyMemberHistory.condition.code"
  * andereSE -> "FamilyMemberHistory.condition.code"
  * penetranz -> "FamilyMemberHistory.extension.where(url='https://www.medizininformatik-initiative.de/fhir/ext/modul-seltene/StructureDefinition/mii-ex-seltene-penetrance').valueCodeableConcept"
  * familienmitgliedVerstorben -> "FamilyMemberHistory.deceasedBoolean"
* therapieForschung -> "CarePlan | MedicationRequest | ResearchStudy"
  * offLabel -> "MedicationRequest.extension"
    * offLabelGabe -> "MedicationRequest.extension.where(url='http://hl7.org/fhir/StructureDefinition/resource-pertainsToGoal').valueBoolean"
    * offLabelMedikament -> "MedicationRequest.medicationCodeableConcept"
  * studie -> "ResearchStudy | ServiceRequest.where(code.coding.exists(code='study-enrollment'))"
    * studienID -> "ResearchStudy.identifier"
    * studienStatus -> "ResearchStudy.status"
    * studienzeitraum -> "ResearchStudy.period"
  * therapie -> "CarePlan"
    * therapieempfehlung -> "MedicationRequest | ServiceRequest"
    * durchgefuehrteTherapie -> "Procedure | MedicationStatement"
    * startdatumTherapie -> "CarePlan.period.start"
    * enddatumTherapie -> "CarePlan.period.end"
    * grundEndeTherapie -> "CarePlan.activity.outcomeCodeableConcept"


Mapping: SE-vomLogicalModelzuNARSE
Id: NARSE
Title: "SE LogicalModel NARSE Mapping"
Source: MII_LM_SE
Target: "https://www.se-atlas.de/narse"
* anamneseUndDiagnostik -> "-"
  * untersuchungsdatum -> "Nicht vorhanden"
  * phaenotypisierung -> "-"
    * hpoTerm -> "AnamneseUndDiagnostik.Phänotyp:HPOTerm"
    * hpoStatus -> "Nicht vorhanden"
    * hpoVersion -> "Katalog mit vorhanden unter AnamneseUndDiagnostik.Phänotyp:HPOTerm"
    * zeitraumSymptom -> "-"
      * zeitraumSymptom -> "Nicht vorhanden"
      * lebensphase -> "Ähnlich zu AlterBeiErstenSymptomen:AuswahlDerAltersangabe; allerdings anderes ValueSet"
      * alterSymptom -> "AnamneseUndDiagnostik.AlterBeiErstenSymptomen:Alter "
    * verlaufSymptom -> "Nicht vorhanden"
  * klinischeDiagnose -> "-"
    * zeitpunktKlinischeDia -> "Ähnlich zu AnamneseUndDiagnostikAlterBeiDiagnose:AuswahlDerAltersangabe; allerdings anderes ValueSet"
    * feststellungsdatumKlinischeDia -> "Nicht vorhanden"
    * alterKlinischeDia -> "AnamneseUndDiagnostik.AlterBeiDiagnose:Alter"
  * genetischeDiagnose -> "-"
    * zeitpunktGenDia -> "Ähnlich zu AnamneseUndDiagnostikAlterBeiDiagnose:AuswahlDerAltersangabe; allerdings anderes ValueSet und nicht auf genetische Diagnose beschränkt"
    * feststellungsdatumGenDia -> "Nicht vorhanden"
    * alterGenDia -> "Kann zu AnamneseUndDiagnostik.AlterBeiDiagnose:Alter zugeordnet werden; im NARSE jedoch nicht auf genetische Diagnose beschränkt"
  * genDiaFehlendePenetranz -> "Nicht vorhanden"
  * methodeDiagnosestellung -> "anamneseUndDiagnostik.Diagnosestellung"
* koerperlicheUntersuchung -> "-"
  * koerpergewicht -> "-"
    * koerpergewicht -> "Nicht vorhanden"
    * datumKoerpergewicht -> "Nicht vorhanden"
  * koerpergroesse -> "-"
    * koerpergroesse -> "Nicht vorhanden"
    * datumKoerpergroesse -> "Nicht vorhanden"
  * bmi -> "-"
    * bmi -> "Nicht vorhanden"
    * datumBMI -> "Nicht vorhanden"
  * kopfumfang -> "-"
    * kopfumfang -> "Nicht vorhanden"
    * datumKopfumfang -> "Nicht vorhanden"
  * bauchumfang -> "-"
    * bauchumfang -> "Nicht vorhanden"
    * datumBauchumfang -> "Nicht vorhanden"
  * hueftumfang -> "-"
    * hueftumfang -> "Nicht vorhanden"
    * datumHueftumfang -> "Nicht vorhanden"
  * blutgruppe -> "Nicht vorhanden"
* persoenlicheInfosIndexpatient -> "-"
  * tod -> "-"
    * sterbedatum -> "Nicht direkt vorhanden, wird im NARSE nur durch PersönlicherUndFamiliärerHintergrund.Sterbealter abgebildet."
    * anSEVerstorben -> "PersönlicherUndFamiliärerHintergrund.AnSeVerstorben "
    * andereTodesursache -> "PersönlicherUndFamiliärerHintergrund.AndereTodesursache "
* familienanamnese -> "PersönlicherUndFamiliärerHintergrund"
  * verwandtschaftsverhaeltnis -> "PersönlicherUndFamiliärerHintergrund.BetroffeneFamilienangehörige:Verwandtschaftsbeziehung"
  * geschlecht -> "Nicht vorhanden"
  * gleicheSE -> "PersönlicherUndFamiliärerHintergrund.BetroffeneFamilienangehörige:SelteneErkrankung"
  * andereSE -> "Nicht vorhanden"
  * penetranz -> "Nicht vorhanden"
  * familienmitgliedVerstorben -> "PersönlicherUndFamiliärerHintergrund.BetroffeneFamilienangehörigeVerstorben?"
* therapieForschung -> "anamneseUndDiagnostik"
  * offLabel -> "Nicht vorhanden"
    * offLabelGabe -> "Nicht vorhanden"
    * offLabelMedikament -> "Nicht vorhanden"
  * studie -> "Nicht vorhanden"
    * studienID -> "Nicht vorhanden"
    * studienStatus -> "Nicht vorhanden"
    * studienzeitraum -> "Nicht vorhanden"
  * therapie -> "Nicht vorhanden"
    * therapieempfehlung -> "Nicht vorhanden"
    * durchgefuehrteTherapie -> "anamneseUndDiagnostik.Therapiestatus"
    * startdatumTherapie -> "Nicht vorhanden"
    * enddatumTherapie -> "Nicht vorhanden"
    * grundEndeTherapie -> "Nicht vorhanden"

Mapping: SE-vomLogicalModelzumERDRICDS
Id: ERDRICDS
Title: "SE LogicalModel ERDRI CDS Mapping"
Source: MII_LM_SE
Target: "https://eu-rd-platform.jrc.ec.europa.eu/set-of-common-data-elements_en"
* anamneseUndDiagnostik -> "-"
  * untersuchungsdatum -> "Nicht vorhanden"
  * phaenotypisierung -> "-"
    * hpoTerm -> "Nur beim nicht diagnostiziertem Fall unter Diagnose.NichtDiagnostizierterFall"
    * hpoStatus -> "Nicht vorhanden"
    * hpoVersion -> "Nicht vorhanden"
    * zeitraumSymptom -> "-"
      * zeitraumSymptom -> "Krankheitsverlauf.AlterBeiKrankheitsbeginn unter Datum(TT/MM/JJJJ) "
      * lebensphase -> "Krankheitsverlauf.AlterBeiKrankheitsbeginn; aber anderes ValueSet"
      * alterSymptom -> "Nicht vorhanden"
    * verlaufSymptom -> "Nicht vorhanden"
  * klinischeDiagnose -> "-"
    * zeitpunktKlinischeDia -> "Ähnlich zu Krankheitsverlauf.AlterBeiDiagnose; allerdings anderes ValueSet"
    * feststellungsdatumKlinischeDia -> "Krankheitsverlauf.AlterBeiDiagnose unter Datum(TT/MM/JJJJ)"
    * alterKlinischeDia -> "Nicht vorhanden"
  * genetischeDiagnose -> "-"
    * zeitpunktGenDia -> "Ähnlich zu Krankheitsverlauf.AlterBeiDiagnose; allerdings anderes ValueSet und nicht auf genetische Diagnose beschränkt"
    * feststellungsdatumGenDia -> "Krankheitsverlauf.AlterBeiDiagnose unter Datum(TT/MM/JJJJ), aber nicht auf genetische Diagnose beschränkt"
    * alterGenDia -> "Nicht vorhanden"
  * genDiaFehlendePenetranz -> "Nicht vorhanden"
  * methodeDiagnosestellung -> "Nicht vorhanden"
* koerperlicheUntersuchung -> "-"
  * koerpergewicht -> "Nicht vorhanden"
    * koerpergewicht -> "Nicht vorhanden"
    * datumKoerpergewicht -> "Nicht vorhanden"
  * koerpergroesse -> "Nicht vorhanden"
    * koerpergroesse -> "Nicht vorhanden"
    * datumKoerpergroesse -> "Nicht vorhanden"
  * bmi -> "Nicht vorhanden"
    * bmi -> "Nicht vorhanden"
    * datumBMI -> "Nicht vorhanden"
  * kopfumfang -> "Nicht vorhanden"
    * kopfumfang -> "Nicht vorhanden"
    * datumKopfumfang -> "Nicht vorhanden"
  * bauchumfang -> "Nicht vorhanden"
    * bauchumfang -> "Nicht vorhanden"
    * datumBauchumfang -> "Nicht vorhanden"
  * hueftumfang -> "Nicht vorhanden"
    * hueftumfang -> "Nicht vorhanden"
    * datumHueftumfang -> "Nicht vorhanden"
  * blutgruppe -> "Nicht vorhanden"
* persoenlicheInfosIndexpatient -> "-"
  * tod -> "-"
    * sterbedatum -> "Patientenstatus.Todeszeitpunkt"
    * anSEVerstorben -> "Nicht vorhanden"
    * andereTodesursache -> "Nicht vorhanden"
* familienanamnese -> "-"
  * verwandtschaftsverhaeltnis -> "Nicht vorhanden"
  * geschlecht -> "Nicht vorhanden"
  * gleicheSE -> "Nicht vorhanden"
  * andereSE -> "Nicht vorhanden"
  * penetranz -> "Nicht vorhanden"
  * familienmitgliedVerstorben -> "Nicht vorhanden"
* therapieForschung -> "-"
  * offLabel -> "-"
    * offLabelGabe -> "Nicht vorhanden"
    * offLabelMedikament -> "Nicht vorhanden"
  * studie -> "-"
    * studienID -> "Nicht vorhanden"
    * studienStatus -> "Nicht vorhanden"
    * studienzeitraum -> "Nicht vorhanden"
  * therapie -> "-"
    * therapieempfehlung -> "Nicht vorhanden"
    * durchgefuehrteTherapie -> "Nicht vorhanden"
    * startdatumTherapie -> "Nicht vorhanden"
    * enddatumTherapie -> "Nicht vorhanden"
    * grundEndeTherapie -> "Nicht vorhanden"


Mapping: SE-vomLogicalModelzumModellvorhabenGenomsequenzierung
Id: ModellvorhabenGenomsequenzierung
Title: "SE LogicalModel ModellvorhabenGenomsequenzierung Mapping"
Source: MII_LM_SE
Target: "https://www.medizininformatik-initiative.de/de/modellvorhaben-genomsequenzierung"
* anamneseUndDiagnostik -> "-"
  * untersuchungsdatum -> "Nicht direkt vorhanden; gibt nur Daten für vergangene Diagnostik, Proben, etc."
  * phaenotypisierung -> "-"
    * hpoTerm -> "diagnosisRd.phenotypes[].code+text oder followUpRd.phenotypes[].code (Angabe mit code, text, system und display) "
    * hpoStatus -> "Nicht vorhanden"
    * hpoVersion -> "Angabe unter system bei phenotypes[].code"
    * zeitraumSymptom -> "-"
      * zeitraumSymptom -> "diagnosisRd.symptomOnsetDate (Monat und Jahr des Beginns des ersten aufgetretenen HPO-kodierten Symptoms) "
      * lebensphase -> "Nicht vorhanden"
      * alterSymptom -> "Nicht vorhanden"
    * verlaufSymptom -> "followUpRd.phenotypes[].change (anderes ValueSet: newlyAdded, improved, degraded, noLongerObserved,unchanged)"
  * klinischeDiagnose -> "-"
    * zeitpunktKlinischeDia -> "Nicht vorhanden"
    * feststellungsdatumKlinischeDia -> "Nicht direkt bei RareDiseasesCase; jedoch allgemein: mainDiagnosis.date oder additionalDiagnoses[].date (Datum der Hauptdiagnose im ISO 8601 Format JJJJ-MM-TT. Wenn Tag unbekannt -> 15. des Monats)"
    * alterKlinischeDia -> "Nicht vorhanden"
  * genetischeDiagnose -> "-"
    * zeitpunktGenDia -> "Nicht vorhanden"
    * feststellungsdatumGenDia -> "Nicht direkt bei RareDiseasesCase; jedoch allgemein: mainDiagnosis.date oder additionalDiagnoses[].date (Datum der Hauptdiagnose im ISO 8601 Format JJJJ-MM-TT. Wenn Tag unbekannt -> 15. des Monats), aber nicht auf genetische Diagnose beschränkt"
    * alterGenDia -> "Nicht vorhanden"
  * genDiaFehlendePenetranz -> "Nicht vorhanden"
  * methodeDiagnosestellung -> "Nicht vorhanden"
* koerperlicheUntersuchung -> "-"
  * koerpergewicht -> "Nicht vorhanden"
    * koerpergewicht -> "Nicht vorhanden"
    * datumKoerpergewicht -> "Nicht vorhanden"
  * koerpergroesse -> "Nicht vorhanden"
    * koerpergroesse -> "Nicht vorhanden"
    * datumKoerpergroesse -> "Nicht vorhanden"
  * bmi -> "Nicht vorhanden"
    * bmi -> "Nicht vorhanden"
    * datumBMI -> "Nicht vorhanden"
  * kopfumfang -> "Nicht vorhanden"
    * kopfumfang -> "Nicht vorhanden"
    * datumKopfumfang -> "Nicht vorhanden"
  * bauchumfang -> "Nicht vorhanden"
    * bauchumfang -> "Nicht vorhanden"
    * datumBauchumfang -> "Nicht vorhanden"
  * hueftumfang -> "Nicht vorhanden"
    * hueftumfang -> "Nicht vorhanden"
    * datumHueftumfang -> "Nicht vorhanden"
  * blutgruppe -> "Nicht vorhanden"
* persoenlicheInfosIndexpatient -> "-"
  * tod -> "-"
    * sterbedatum -> "followUpRd.deathDate (Sterbemonat und Sterbejahr, Datum"
    * anSEVerstorben -> "Nicht vorhanden"
    * andereTodesursache -> "Nicht vorhanden"
* familienanamnese -> "-"
  * verwandtschaftsverhaeltnis -> "Nicht vorhanden"
  * geschlecht -> "Nicht vorhanden"
  * gleicheSE -> "Nicht vorhanden"
  * andereSE -> "Nicht vorhanden"
  * penetranz -> "Nicht vorhanden"
  * familienmitgliedVerstorben -> "Nicht vorhanden"
* therapieForschung -> "-"
  * offLabel -> "-"
    * offLabelGabe -> "Nicht identisch, aber unter recommendedSystemicTherapies.type (offLabel) möglich"
    * offLabelMedikament -> "Nicht identisch, aber unter recommendedSystemicTherapies.substances[].code/.version möglich"
  * studie -> "-"
    * studienID -> "Nur Empfehlung, nicht tatsächliche Studie recommendedStudies.identifier und recommendedStudies.id"
    * studienStatus -> "recommendedStudies.name"
    * studienzeitraum -> "Nicht vorhanden"
  * therapie -> "-"
    * therapieempfehlung -> "Nicht identisch RareDiseasesPlan.recommendedTherapies.strategy (Anderes ValueSet: systemicMedication, targetedMedication, preventionMedication, geneTherapy, prophylactic, earlyDetection, combination, nutrition, other); Angabe unter recommendedTherapies.strategyOther möglich"
    * durchgefuehrteTherapie -> "recommendedSystemicTherapies.therapeuticStrategy (Anderes ValueSet)"
    * startdatumTherapie -> "therapies.therapyStartDate (allerdings unter OncologyFollowUp nicht unter RareDiseasesCase (Startdatum der fallrelevante,systemische Vortherapie))"
    * enddatumTherapie -> "therapies.therapyEndDate (allerdings unter OncologyFollowUp nicht unter RareDiseasesCase (Enddatum der fallrelevante,systemische Vortherapie))"
    * grundEndeTherapie -> "therapies.terminationReasonOBDS (allerdings unter OncologyFollowUp nicht unter RareDiseasesCase; ValueSet: E = reguläres Ende; R = reguläres Ende mit Dosisreduktion; W = reguläres Ende mit Substanzwechsel; A = Abbruch wegen Nebenwirkungen; P = Abbruch wegen Progress; S = Abbruch aus sonstigen Gründen; V= Patient verweigert weitere Therapie ;T= Patient verstorben; U = unbekannt)"
*/